version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./python/Dockerfile
    working_dir: /usr/src
    environment:
      # https://h2oai.github.io/wave/docs/configuration#configuring-your-app
      - H2O_APP_ADDRESS=http://server:8000
      - H2O_WAVE_ADDRESS=http://server:10101
    volumes:
      - .:/usr/src
    depends_on:
      - server
    tty: true
    command: wave run app.py

  server:
    build:
      context: .
      dockerfile: ./wave/Dockerfile
      args:
        - WAVE_VERSION=0.19.0
    working_dir: /usr/wave
    command: ./waved
    ports:
      - '10101:10101'