version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./python/Dockerfile
    working_dir: /usr/src
    volumes:
      - ./:/usr/src
    depends_on:
      - server
    tty: true
    command: wave run app.py

  server:
    build:
      context: .
      dockerfile: ./wave/Dockerfile
      args:
        - WAVE_VERSION=0.19.0
    working_dir: /usr/wave
    command: ./waved